addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.10")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M12-1")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "1.5.1")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "0.2.11")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0-M2")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.8.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.2.0")
// addSbtPlugin("com.typesafe.sbt" %% "sbt-web" % "1.4.0")
// addSbtPlugin("com.typesafe.sbt" % "sbt-js-engine" % "1.1.4")
// addSbtPlugin("org.wartremover" % "sbt-wartremover" % "1.0.0")
// addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.5")
// addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")
