addSbtPlugin("com.dwijnand" % "sbt-dynver" % "1.1.0")
// addSbtPlugin("com.fortysevendeg"       % "sbt-microsites"      % "0.4.0")
addSbtPlugin("com.geirsson"            % "sbt-scalafmt" % "0.6.8")
addSbtPlugin("com.softwaremill.clippy" % "plugin-sbt"   % "0.5.2")
// addSbtPlugin("com.typesafe.sbt"        % "sbt-ghpages"         % "0.6.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0-M8")
// addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.3.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "1.8.0")
addSbtPlugin("io.get-coursier"   % "sbt-coursier" % "1.0.0-RC1")
addSbtPlugin("io.spray"          % "sbt-revolver" % "0.8.0")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"  % "0.6.16")
// addSbtPlugin("org.tpolecat"            % "tut-plugin"          % "0.4.8")
// addSbtPlugin("org.wartremover" % "sbt-wartremover" % "1.0.0")
// addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.4")
